import fs from "node:fs";
import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
await build({entryPoints:['worker/contact.ts'],outfile:'/tmp/hikes-contact.mjs',bundle:true,platform:'node',format:'esm'});const {validateSubmission,issuePayload,ContactHandler}=await import('/tmp/hikes-contact.mjs');
const sample={kind:'correction',title:'Trail correction',message:'The trail length should be checked against this source.',source:'https://example.invalid/source',trailId:'ofer',language:'en',requestId:'12345678-1234-1234-1234-123456789abc',token:'token',consent:true,website:''};
const env={CONTACT_ENABLED:'true',CONTACT_HOSTNAME:'hikes.example',TURNSTILE_SITE_KEY:'site',TURNSTILE_SECRET_KEY:'secret',GITHUB_ISSUES_TOKEN:'fake-test-token'};
class Store{rows=new Map();async get(k){return this.rows.get(k)}async put(k,v){this.rows.set(k,v)}async delete(k){for(const x of Array.isArray(k)?k:[k])this.rows.delete(x)}async list(){return this.rows}async getAlarm(){return 1}async setAlarm(){}}
const req=(v=sample,headers={})=>new Request('https://hikes.example/api/contact',{method:'POST',headers:{Origin:'https://hikes.example','Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...headers},body:JSON.stringify(v)});
const setup=(verification={success:true,hostname:'hikes.example',action:'contact'},issueStatus=201)=>{const store=new Store(),calls=[];const f=async(url,opt)=>{calls.push({url,opt});return url.includes('siteverify')?Response.json(verification):Response.json({html_url:'https://github.com/asnir/israel-hikes/issues/100'}, {status:issueStatus})};return {handler:new ContactHandler(store,env,f,()=>1800000000000),store,calls}};
test('Submission rejects personal fields, private URLs, invalid length and missing consent',()=>{assert.ok(validateSubmission(sample));for(const patch of [{consent:false},{message:'Email me at person@example.com'},{message:'Call 0541234567 for trail details'},{source:'javascript:alert(1)'},{source:'https://docs.google.com/document/d/private'},{website:'bot'},{token:''},{title:'x'},{requestId:'x'}])assert.equal(validateSubmission({...sample,...patch}),null)});
test('Issue template labels unverified content, neutralizes mentions and never creates a PR',()=>{const out=issuePayload({...sample,message:'@owner <script> *please run code*'});assert.ok(out.body.includes('Unverified visitor'));assert.ok(!out.body.includes('@owner'));assert.ok(!out.body.includes('<script>'));assert.ok(!('head'in out));assert.ok(out.title.startsWith('[Website correction]'))});
test('Valid CAPTCHA creates exactly one issue and repeated request returns receipt',async()=>{const {handler,calls,store}=setup();assert.equal((await handler.fetch(req())).status,201);assert.equal((await handler.fetch(req())).status,200);assert.equal(calls.length,2);assert.equal(calls[1].url,'https://api.github.com/repos/asnir/israel-hikes/issues');assert.ok(!JSON.stringify([...store.rows]).includes('192.0.2.1'));assert.ok(!JSON.stringify([...store.rows]).includes(sample.message))});
test('Fail closed on invalid CAPTCHA hostname/action and disabled config',async()=>{for(const verification of [{success:false},{success:true,hostname:'evil.example',action:'contact'},{success:true,hostname:'hikes.example',action:'login'}]){const {handler,calls}=setup(verification);assert.equal((await handler.fetch(req())).status,400);assert.equal(calls.length,1)}assert.equal((await new ContactHandler(new Store(),{},async()=>{throw Error()}).fetch(req())).status,503)});
test('Origin, body size and rate limit are enforced before GitHub',async()=>{const {handler,calls}=setup();assert.equal((await handler.fetch(req(sample,{Origin:'https://evil.example'}))).status,403);assert.equal((await handler.fetch(req({...sample,message:'x'.repeat(13000)}))).status,413);assert.equal((await handler.fetch(req())).status,201);assert.equal((await handler.fetch(req({...sample,requestId:'12345678-1234-1234-1234-123456789abd'}))).status,429);assert.equal(calls.length,2)});
test('Ambiguous GitHub failure is not retried into duplicate issues',async()=>{const {handler,calls}=setup(undefined,502);assert.equal((await handler.fetch(req())).status,502);assert.equal((await handler.fetch(req())).status,409);assert.equal(calls.length,2)});

test('Daily global cap and expired metadata cleanup work without storing submissions',async()=>{const {handler,store,calls}=setup();store.rows.set('contact-global:2027-01-15',{count:25});const day=new Date(1800000000000).toISOString().slice(0,10);store.rows.set('contact-global:'+day,{count:25});assert.equal((await handler.fetch(req())).status,429);assert.equal(calls.length,0);store.rows.set('expired',{expires:1});await handler.alarm();assert.ok(!store.rows.has('expired'))});

test('Production build config disables sourcemaps and site source has no GitHub links',()=>{assert.match(fs.readFileSync('vite.config.ts','utf8'),/sourcemap:false/);for(const file of ['src/pages/Contact.tsx','src/pages/AccessibilityStatement.tsx','src/pages/About.tsx'])assert.ok(!/https:\/\/github\.com/.test(fs.readFileSync(file,'utf8')))});
