import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
function runtimeRss(){const rows=spawnSync('ps',['-eo','pid,ppid,rss,comm'],{encoding:'utf8'}).stdout.trim().split('\n').slice(1).map(s=>s.trim().split(/\s+/));const descendants=new Set([String(process.pid)]);let more=true;while(more){more=false;for(const r of rows)if(descendants.has(r[1])&&!descendants.has(r[0])){descendants.add(r[0]);more=true;}}return rows.filter(r=>descendants.has(r[0])&&r[3].includes('workerd')).map(r=>({pid:Number(r[0]),rssKiB:Number(r[2])}));}
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const fixture=`import {loadPasswordHasher} from './worker/password-runtime';export default{async fetch(){try{const h=await loadPasswordHasher();const p=new Uint8Array(32).fill(41),s=new Uint8Array(16).fill(7);const out=await h({password:p,salt:s,passes:2,memorySize:19456,parallelism:1,tagLength:32});p.fill(0);s.fill(0);const good=out.some(b=>b!==0);out.fill(0);return Response.json({good,probe:globalThis.__probe});}catch{return new Response('unavailable',{status:503})}}}`;
await build({stdin:{contents:fixture,resolveDir:process.cwd(),sourcefile:'load-test.ts'},outfile:'/tmp/disposable-workerd-load.mjs',bundle:true,format:'esm',platform:'browser',plugins:[{name:'probe',setup(b){b.onLoad({filter:/password-runtime\.ts$/},async a=>({contents:(await fs.promises.readFile(a.path,'utf8')).replace('before = memory.buffer;', 'before = memory.buffer;globalThis.__probe={size:before.byteLength,same:false,zero:false,standalone:false};').replace('return out;', 'globalThis.__probe.same=memory.buffer===before;globalThis.__probe.standalone=out.buffer!==before;return out;').replace('if (before && before.byteLength) new Uint8Array(before).fill(0);','if (before && before.byteLength) new Uint8Array(before).fill(0);if(sodium)globalThis.__probe.zero=new Uint8Array(sodium.libsodium.__capturedMemory.buffer).every(b=>b===0);'),loader:'ts'}));b.onResolve({filter:/sodium\.wasm$/},()=>({path:'./sodium.wasm',external:true}));}}]});
test('real workerd 40 serial and 20 concurrent fixed-input attempts keep captured heap intact and zero; contention fails closed',async()=>{
const mf=new Miniflare(convertV4MiniflareOptions({modules:[{type:'ESModule',path:'/tmp/disposable-workerd-load.mjs'},{type:'CompiledWasm',path:'/tmp/sodium.wasm',contents:fs.readFileSync('worker/vendor/libsodium/sodium.wasm')}],modulesRoot:'/tmp',compatibilityDate:'2026-10-09'}));
const check=async r=>{assert.equal(r.status,200);const j=await r.clone().json();assert.equal(j.good,true);assert.deepEqual(j.probe,{size:33554432,same:true,zero:true,standalone:true});};
try{for(let i=0;i<40;i++)await check(await mf.dispatchFetch('https://synthetic.invalid/'));const batch=await Promise.all(Array.from({length:20},()=>mf.dispatchFetch('https://synthetic.invalid/')));assert.ok(batch.some(r=>r.status===200));assert.ok(batch.every(r=>r.status===200||r.status===503));for(const r of batch)if(r.status===200)await check(r);console.log(JSON.stringify({serial:40,concurrent:20,success:batch.filter(r=>r.status===200).length,busy:batch.filter(r=>r.status===503).length,hostRss:process.memoryUsage().rss}));await check(await mf.dispatchFetch('https://synthetic.invalid/'));const rss=[];for(let batchNo=0;batchNo<3;batchNo++){for(let j=0;j<20;j++)await check(await mf.dispatchFetch('https://synthetic.invalid/'));if(global.gc)global.gc();rss.push({batchNo,nodeRss:process.memoryUsage().rss,workerd:runtimeRss()});}console.log(JSON.stringify({rss,forcedNodeGc:typeof global.gc==='function',workerdGc:'not exposed'}));}finally{await mf.dispose();}
});
