import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const photos=JSON.parse(fs.readFileSync('src/data/photos.json'));const component=fs.readFileSync('src/components/AreaPhoto.tsx','utf8');
test('Every regional photograph has a local asset and complete individual rights metadata',()=>{assert.equal(Object.keys(photos).length,9);for(const p of Object.values(photos)){assert.ok(fs.statSync('public'+p.src).size>1000);for(const key of ['title','author','source','licence','licenceUrl','changes'])assert.ok(p[key]);assert.match(p.source,/^https:\/\/commons.wikimedia.org\/wiki\/File:/);assert.ok(p.licenceUrl.startsWith('http'));}});
test('Area context never claims exact trail or current-condition photography',()=>{assert.match(component,/not the specific trail or current conditions/);assert.match(component,/Not a photograph of this specific trail/);assert.match(component,/p\.author/);assert.match(component,/p\.licenceUrl/);assert.match(component,/p\.changes/)});
test('Grouped Carmel area uses separate Gilboa and Menashe images and known long-route groups',()=>{assert.match(component,/פארק המעיינות/);assert.match(component,/return "gilboa"/);assert.match(component,/return "menashe"/);assert.match(component,/seg-y2y-/);assert.match(component,/seg-jer-/)});
test('Trail-site photographs have bilingual honest captions and rights',()=>{const exact=JSON.parse(fs.readFileSync('src/data/trail-photos.json'));assert.deepEqual(Object.keys(exact).sort(),['ext-10','ext-112','ext-137','ext-26','ext-44','ext-64','ext-89','ext-96','hanadiv','ofer','oren','shofet']);for(const p of Object.values(exact)){assert.ok(fs.statSync('public'+p.src).size>1000);for(const key of ['title','author','source','licence','licenceUrl','changes','captionHe','captionEn','authorEn'])assert.ok(p[key]);assert.ok(!/[א-ת]/.test(p.captionEn+p.authorEn));assert.match(p.source,/^https:\/\/commons.wikimedia.org\/wiki\/File:/);assert.match(p.captionEn,/current/);}assert.match(component,/specific \|\|/)});

test('List thumbnails use only checked per-trail photos, with linked rights and placeholders',()=>{const exact=JSON.parse(fs.readFileSync('src/data/trail-photos.json'));for(const p of Object.values(exact))assert.ok(fs.statSync('public'+p.thumbSrc).size>1000);const card=fs.readFileSync('src/components/TrailCard.tsx','utf8');assert.match(card,/photo\.thumbSrc/);assert.match(card,/photo\.licence/);assert.match(card,/card-landscape/);assert.ok(!card.includes('data/photos.json'))});

test('List thumbnail links to visible trail credit and retains descriptive author/license alt',()=>{const card=fs.readFileSync('src/components/TrailCard.tsx','utf8');assert.match(card,/<Link className="card-photo" to=\{"\/trail\/"\+t.id\}/);assert.ok(card.includes('photo.authorEn'));assert.ok(card.includes('photo.licence'));assert.ok(!card.includes('<figcaption>'));const page=fs.readFileSync('src/components/AreaPhoto.tsx','utf8');assert.ok(page.includes('<figcaption>'));assert.ok(page.includes('p.licenceUrl'))});
