import { language } from "../i18n";
export default function AccessibilityStatement(){const he=language()==='he';return <main id="main" className="page detail"><h1>{he?'הצהרת נגישות':'Accessibility statement'}</h1>
<p>{he?'עודכן ב-9 באוקטובר 2026. מטרת האתר היא לאפשר שימוש נוח בעברית ובאנגלית, גם באמצעות מקלדת וטכנולוגיות מסייעות.':'Updated on 9 October 2026. We aim to make this site usable in Hebrew and English, including with a keyboard and assistive technology.'}</p>
<h2>{he?'מה יושם':'What has been implemented'}</h2>
<ul>{(he?['מבנה כותרות וציוני דרך, קישור דילוג לתוכן ותוויות לשדות.','ניווט במקלדת ומיקוד גלוי; כרטיסי המסלולים הם חלופה למפה.','כיוון RTL בעברית ו-LTR באנגלית, ותיאורי חלופה לתמונות.','אפשרויות להגדלת טקסט, ניגודיות גבוהה, צמצום תנועה והדגשת קישורים.']:['Headings and landmarks, a skip-to-content link and labelled fields.','Keyboard navigation and visible focus; trail cards provide an alternative to the map.','Hebrew RTL and English LTR layout, with alternative text for images.','Controls for larger text, high contrast, reduced motion and underlined links.']).map(s=><li key={s}>{s}</li>)}</ul>
<h2>{he?'בדיקות ומגבלות':'Checks and limitations'}</h2>
<p>{he?'נבדקו תצוגות ברוחב 390 ו-1440 פיקסלים וניווט בסיסי במקלדת, לצד בדיקות אוטומטיות. הבדיקות אינן אישור לעמידה מלאה בתקן הישראלי ת״י 5568 או ב-WCAG. טרם בוצעה ביקורת נגישות עצמאית עם משתמשי קורא מסך.':'Layouts at 390 and 1440 pixels, basic keyboard use and automated checks have been reviewed. These checks do not certify full compliance with Israeli Standard 5568 or WCAG. An independent accessibility audit with screen-reader users has not yet been completed.'}</p>
<p>{he?'מפות אינטראקטיביות ושירותי ניווט חיצוניים עשויים להיות פחות נגישים ואינם בשליטתנו. מידע המסלול, נקודת ההתחלה והמקורות מוצגים גם כטקסט. כפתור הנגישות אינו תחליף לנגישות האתר ואינו ערובה משפטית.':'Interactive maps and external navigation services may be less accessible and are outside our control. Trail information, start points and sources are also available as text. The accessibility menu does not replace accessible design or provide a legal guarantee.'}</p>
<p>{he?'ערוץ פניות אינו זמין כרגע באתר.':'A contact channel is not currently available on this site.'}</p>
</main>}
