import {useEffect,useRef,useState} from 'react';import {language} from '../i18n';
declare global {interface Window {turnstile?:{render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void}}}
export default function Contact(){const he=language()==='he',widget=useRef<HTMLDivElement>(null),widgetId=useRef('');const [config,C]=useState<{enabled:boolean;siteKey:string}|null>(null),[token,T]=useState(''),[kind,K]=useState('correction'),[title,H]=useState(''),[message,M]=useState(''),[source,U]=useState(''),[trailId,I]=useState(''),[consent,A]=useState(false),[preview,P]=useState(false),[busy,B]=useState(false),[status,S]=useState(''),[issue,J]=useState('');const requestId=useRef(crypto.randomUUID());
 useEffect(()=>{fetch('/api/contact-config').then(r=>r.json()).then(C).catch(()=>C({enabled:false,siteKey:''}))},[]);
 useEffect(()=>{if(!config?.enabled||!config.siteKey||!widget.current)return;let cancelled=false;const render=()=>{if(!cancelled&&window.turnstile&&widget.current)widgetId.current=window.turnstile.render(widget.current,{sitekey:config.siteKey,action:'contact',language:he?'he':'en',size:'flexible',callback:T,'expired-callback':()=>T(''),'error-callback':()=>{T('');S(he?'האימות נכשל. נסו שוב.':'Verification failed. Try again.')}})};let script=document.querySelector<HTMLScriptElement>('script[data-contact-turnstile]');if(window.turnstile)render();else{if(!script){script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.dataset.contactTurnstile='true';document.head.append(script)}script.addEventListener('load',render)}return()=>{cancelled=true;script?.removeEventListener('load',render);if(widgetId.current)window.turnstile?.remove(widgetId.current);T('')}},[config,he,preview]);
 const send=async()=>{B(true);S('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,title,message,source,trailId,language:he?'he':'en',consent,token,requestId:requestId.current,website:''})});const data=await r.json();if(r.ok&&data.receipt){J(data.receipt);S('success')}else{const messages:Record<string,string>=he?{'invalid':'בדקו את השדות. אין לכלול אימייל, טלפון או מסמך פרטי.','rate-limit':'הגעתם למגבלת הגשות. נסו ביום אחר.','verification-failed':'האימות פג או נכשל. בצעו אותו שוב.','pending-review':'לא ניתן לאשר אם נוצר דיווח. אל תשלחו שוב מיד. שמרו את מזהה ההגשה.'}:{'invalid':'Check the fields. Do not include email, phone or private documents.','rate-limit':'Submission limit reached. Try another day.','verification-failed':'Verification expired or failed. Complete it again.','pending-review':'We cannot confirm whether a report was created. Do not immediately resubmit. Keep the submission ID.'};S(messages[data.error]||(he?'השירות אינו זמין כרגע. נסו מאוחר יותר.':'The service is unavailable. Try later.'));window.turnstile?.reset(widgetId.current);T('')}}catch{S(he?'לא ניתן לאשר שההגשה התקבלה. שמרו את מזהה ההגשה ואל תשלחו שוב מיד.':'Submission could not be confirmed. Keep the submission ID and do not immediately resubmit.')}finally{B(false)}};
 return <main id="main" className="page detail contact-page"><h1>{he?'הצעה, תיקון או יצירת קשר':'Suggest a trail, correction or contact us'}</h1><p>{he?'הטופס מפרסם דיווח ציבורי, לא משנה מסלולים ולא יוצר שינוי קוד. כל שינוי נבדק ומחייב אישור בעל האתר.':'This form publishes a public report. It does not change trails or code. Changes require review and owner approval.'}</p><p className="notice">{he?'כל הטקסט וקישורי המקור יפורסמו לעיני כולם. אין לכלול שם, אימייל, טלפון, מידע רפואי, סודות או מסמך פרטי. זה אינו ערוץ פרטי או שירות חירום.':'All text and source links will be public. Do not include names, email, phone, medical details, secrets or private documents. This is not a private channel or an emergency service.'}</p>
 {!config?.enabled?<p role="status">{he?'הטופס עדיין אינו פעיל. נסו מאוחר יותר.':'The form is not active yet. Try later.'}</p>:<form onSubmit={e=>{e.preventDefault();P(true)}}>
 <label>{he?'סוג הפנייה':'Report type'}<select value={kind} onChange={e=>{K(e.target.value);P(false);A(false)}}><option value="new-trail">{he?'הצעת מסלול':'New trail suggestion'}</option><option value="correction">{he?'תיקון מידע':'Correction'}</option><option value="general">{he?'פנייה כללית':'General contact'}</option></select></label>
 <label>{he?'כותרת':'Title'}<input required minLength={5} maxLength={100} value={title} onChange={e=>{H(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'מזהה מסלול, אם יש':'Trail ID, if relevant'}<input maxLength={80} pattern="[a-z0-9-]*" dir="ltr" value={trailId} onChange={e=>{I(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'תיאור ההצעה או הבעיה':'Description of the suggestion or problem'}<textarea required minLength={20} maxLength={3000} rows={7} value={message} onChange={e=>{M(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'קישור למקור ציבורי, אם יש':'Public source URL, if available'}<input type="url" maxLength={500} dir="ltr" value={source} onChange={e=>{U(e.target.value);P(false);A(false)}}/></label>
 <button className="button primary" type="submit">{he?'בדיקה לפני פרסום':'Review before publishing'}</button>
 {preview&&<section className="contact-preview" aria-label={he?'תצוגת הדיווח הציבורי':'Public report preview'}><h2>{he?'מה יפורסם':'What will be published'}</h2><h3 dir="auto">{title}</h3><p>{he?'סוג':'Type'}: {kind} · {he?'מזהה':'ID'}: {trailId||'-'}</p><p>{he?"שפה":"Language"}: {he?"he":"en"} · {he?"מזהה הגשה":"Submission ID"}: <bdi>{requestId.current}</bdi></p><p className="preserve-lines">{message}</p><p>{source||'-'}</p><p>{he?'הדיווח יסומן כתוכן גולש שלא אומת, ללא אישור לשינוי האתר.':'The report is labelled unverified visitor input, not authorization to change the website.'}</p><label className="contact-consent"><input type="checkbox" checked={consent} onChange={e=>A(e.target.checked)}/>{he?'קראתי את התצוגה ואני מסכים לפרסום התוכן הזה בדיווח ציבורי.':'I reviewed the preview and agree to publish this content in a public report.'}</label><p>{he?"אימות נגד בוטים מופעל באמצעות Cloudflare Turnstile. הדפדפן פונה ל-Cloudflare רק כשפותחים תצוגה זו.":"Bot verification uses Cloudflare Turnstile. Your browser connects to Cloudflare when this preview opens."}</p><div ref={widget}/><button className="button primary" type="button" disabled={!consent||!token||busy||!!issue} onClick={send}>{busy?(he?'שולח…':'Sending…'):(he?'פרסום דיווח ציבורי':'Publish public report')}</button></section>}
 </form>}
 <p role="status" aria-live="polite">{status==='success'?(he?'הדיווח פורסם. אין שינוי אוטומטי באתר.':'Your report was published. No automatic website changes were made.'):status}</p>{issue&&<p>{he?'מזהה קבלה':'Receipt ID'}: <bdi dir="ltr">{issue}</bdi></p>}</main>
}
