import {useEffect,useRef,useState} from 'react';import {language} from '../i18n';
declare global {interface Window {turnstile?:{render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void}}}
export default function Contact(){const he=language()==='he',widget=useRef<HTMLDivElement>(null),widgetId=useRef('');const [config,C]=useState<{enabled:boolean;siteKey:string}|null>(null),[token,T]=useState(''),[kind,K]=useState('correction'),[message,M]=useState(''),[trailId,I]=useState(''),[name,N]=useState(''),[email,E]=useState(''),[consent,A]=useState(false),[preview,P]=useState(false),[busy,B]=useState(false),[status,S]=useState(''),[issue,J]=useState('');const requestId=useRef(crypto.randomUUID());const title=('Contact: '+(trailId||message.slice(0,80))).slice(0,100),source='';
 useEffect(()=>{fetch('/api/contact-config').then(r=>r.json()).then(C).catch(()=>C({enabled:false,siteKey:''}))},[]);
 useEffect(()=>{if(!config?.enabled||!config.siteKey||!widget.current)return;let cancelled=false;const render=()=>{if(!cancelled&&window.turnstile&&widget.current)widgetId.current=window.turnstile.render(widget.current,{sitekey:config.siteKey,action:'contact',language:he?'he':'en',size:'flexible',callback:T,'expired-callback':()=>T(''),'error-callback':()=>{T('');S(he?'האימות נכשל. נסו שוב.':'Verification failed. Try again.')}})};let script=document.querySelector<HTMLScriptElement>('script[data-contact-turnstile]');if(window.turnstile)render();else{if(!script){script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.dataset.contactTurnstile='true';document.head.append(script)}script.addEventListener('load',render)}return()=>{cancelled=true;script?.removeEventListener('load',render);if(widgetId.current)window.turnstile?.remove(widgetId.current);T('')}},[config,he,preview]);
 const send=async()=>{B(true);S('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,title,message,source,trailId,name,email,language:he?'he':'en',consent,token,requestId:requestId.current,website:''})});const data=await r.json();if(r.ok&&data.receipt){J(data.receipt);S('success')}else{const messages:Record<string,string>=he?{'invalid':'בדקו את השדות וכתובת האימייל.','rate-limit':'הגעתם למגבלת הגשות. נסו ביום אחר.','verification-failed':'האימות פג או נכשל. בצעו אותו שוב.','pending-review':'לא ניתן לאשר אם נוצר דיווח. אל תשלחו שוב מיד. שמרו את מזהה ההגשה.'}:{'invalid':'Check the fields and email address.','rate-limit':'Submission limit reached. Try another day.','verification-failed':'Verification expired or failed. Complete it again.','pending-review':'We cannot confirm whether a report was created. Do not immediately resubmit. Keep the submission ID.'};S(messages[data.error]||(he?'השירות אינו זמין כרגע. נסו מאוחר יותר.':'The service is unavailable. Try later.'));window.turnstile?.reset(widgetId.current);T('')}}catch{S(he?'לא ניתן לאשר שההגשה התקבלה. שמרו את מזהה ההגשה ואל תשלחו שוב מיד.':'Submission could not be confirmed. Keep the submission ID and do not immediately resubmit.')}finally{B(false)}};
 return <main id="main" className="page detail contact-page"><h1>{he?'הצעה, תיקון או יצירת קשר':'Suggest a trail, correction or contact us'}</h1><p>{he?'הפנייה נשמרת באופן פרטי לסקירה. אין פרסום אוטומטי, שינוי מסלולים או שינוי קוד. הצעות לשינוי ייבדקו ויחייבו אישור בעל האתר.':'Your submission is stored privately for review. Nothing is automatically published, and no trails or code are changed. Proposed changes require review and owner approval.'}</p><p className="notice">{he?'שדות טקסט בלבד, ללא העלאת קבצים, תמונות או קוד. אין לשלוח סיסמאות, מידע רפואי או מסמכים פרטיים. הפנייה נשמרת עד 30 יום. זה אינו שירות חירום ואין התחייבות למענה.':'Text fields only, with no file, photo or code uploads. Do not send passwords, medical information or private documents. Submissions are kept for up to 30 days. This is not an emergency service and a response is not guaranteed.'}</p>
 {!config?.enabled?<p role="status">{he?'הטופס עדיין אינו פעיל. נסו מאוחר יותר.':'The form is not active yet. Try later.'}</p>:<form onSubmit={e=>{e.preventDefault();P(true)}}>
 <label>{he?'סוג הפנייה':'Report type'}<select value={kind} onChange={e=>{K(e.target.value);P(false);A(false)}}><option value="new-trail">{he?'הצעת מסלול':'New trail suggestion'}</option><option value="correction">{he?'תקלה':'Bug report'}</option><option value="general">{he?'פנייה כללית':'General contact'}</option></select></label>
 <label>{he?'שם (לא חובה)':'Name (optional)'}<input maxLength={80} value={name} onChange={e=>{N(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'אימייל למענה (לא חובה)':'Reply email (optional)'}<input type="email" maxLength={254} dir="ltr" value={email} onChange={e=>{E(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'שם או מזהה מסלול (לא חובה)':'Trail name or ID (optional)'}<input maxLength={80} value={trailId} onChange={e=>{I(e.target.value);P(false);A(false)}}/></label>
 <label>{he?'תיאור ההצעה או הבעיה':'Description of the suggestion or problem'}<textarea required minLength={20} maxLength={3000} rows={7} value={message} onChange={e=>{M(e.target.value);P(false);A(false)}}/></label>
 <button className="button primary" type="submit">{he?'בדיקה לפני שליחה':'Review before sending'}</button>
 {preview&&<section className="contact-preview" aria-label={he?'תצוגת הפנייה':'Submission preview'}><h2>{he?'מה יישלח לסקירה':'What will be sent for review'}</h2><p dir="auto">{name} {email}</p><p>{he?'סוג':'Type'}: {kind==='new-trail'?(he?'הצעת מסלול':'New trail suggestion'):kind==='correction'?(he?'תקלה':'Bug report'):(he?'כללי':'General contact')} · {he?'מזהה':'ID'}: {trailId||'-'}</p><p>{he?"שפה":"Language"}: {he?"he":"en"} · {he?"מזהה הגשה":"Submission ID"}: <bdi>{requestId.current}</bdi></p><p className="preserve-lines">{message}</p><p>{he?'הפנייה תיבדק כתוכן גולש ולא כאישור לשינוי האתר.':'Visitor input is reviewed and is not authorization to change the website.'}</p><label className="contact-consent"><input type="checkbox" checked={consent} onChange={e=>A(e.target.checked)}/>{he?'אני מסכים לשליחת הפנייה לסקירה פרטית.':'I agree to send this submission for private review.'}</label><p>{he?"אימות נגד בוטים מופעל באמצעות Cloudflare Turnstile. הדפדפן פונה ל-Cloudflare רק כשפותחים תצוגה זו.":"Bot verification uses Cloudflare Turnstile. Your browser connects to Cloudflare when this preview opens."}</p><div ref={widget}/><button className="button primary" type="button" disabled={!consent||!token||busy||!!issue} onClick={send}>{busy?(he?'שולח…':'Sending…'):(he?'שליחת פנייה':'Send submission')}</button></section>}
 </form>}
 <p role="status" aria-live="polite">{status==='success'?(he?'הפנייה התקבלה לסקירה פרטית. אין שינוי אוטומטי באתר.':'Your submission was received for private review. No automatic website changes were made.'):status}</p>{issue&&<p>{he?'מזהה קבלה':'Receipt ID'}: <bdi dir="ltr">{issue}</bdi></p>}</main>
}
