import {chromium} from 'playwright';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
const server=spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4175'],{stdio:'ignore'});
try{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));for(let i=0;i<50;i++){try{await page.goto('http://127.0.0.1:4175');break}catch{await new Promise(r=>setTimeout(r,100))}}
await page.waitForSelector('.trail-card');assert.equal(await page.locator('html').getAttribute('lang'),'he');
await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').getAttribute('href'),'#main');
await page.getByRole('button',{name:'5 מסלולים שנבדקו',exact:true}).click();assert.equal(await page.locator('.trail-card').count(),5);
await page.getByRole('button',{name:'שמירת מסלול',exact:true}).first().click();await page.getByRole('button',{name:'English',exact:true}).click();assert.equal(await page.locator('.trail-card').count(),5);
await page.getByRole('button',{name:'Saved (1)',exact:true}).click();assert.equal(await page.locator('.trail-card').count(),1);await page.reload();await page.waitForSelector('.trail-card');assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.getByRole('button',{name:'Saved (1)',exact:true}).count(),1);
await page.getByRole('button',{name:'All trails',exact:true}).click();await page.getByRole('textbox',{name:'Search trails',exact:true}).fill('יער עופר');assert.ok(await page.locator('.trail-card').count()>0);await page.getByRole('textbox',{name:'Search trails',exact:true}).fill('Ofer');assert.ok(await page.locator('.trail-card').count()>0);
await page.locator('.card-title[href="/trail/ofer"]').click();await page.waitForSelector('.detail-heading');const w=await page.getByRole('link',{name:'Waze',exact:true}).getAttribute('href');assert.equal(new URL(w).searchParams.get('navigate'),'yes');assert.ok(await page.getByRole('link',{name:'Google Maps',exact:true}).count());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.getByRole('button',{name:'Accessibility',exact:true}).click();await page.getByLabel('Larger text',{exact:true}).check();assert.ok(await page.locator('html').evaluate(x=>x.classList.contains('large-text')));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Reset',exact:true}).click();await page.getByLabel('Larger text',{exact:true}).focus();await page.keyboard.press('Escape');assert.equal(await page.locator(':focus').innerText(),'Accessibility');
await page.goto('http://127.0.0.1:4175/long');assert.ok(await page.locator('.long-card').count()>0);await page.locator('.long-card').first().click();await page.waitForSelector('.trail-card');assert.ok(await page.locator('.trail-card').count()>0);await page.getByRole('button',{name:'עברית',exact:true}).click();assert.equal(await page.locator('html').getAttribute('dir'),'rtl');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);await browser.close();console.log('Critical UI: keyboard, category preservation, saved persistence, bilingual search, language, navigation and accessibility passed.');}finally{server.kill()}
