import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {mkdirSync} from 'node:fs';import assert from 'node:assert/strict';
const folder=process.env.SCREENSHOT_DIR||'/tmp/preferences-ui';mkdirSync(folder,{recursive:true});const server=spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4192'],{stdio:'ignore'});let browser;
try{browser=await chromium.launch();for(const lang of ['he','en'])for(const width of [390,1440]){
 const context=await browser.newContext({viewport:{width,height:1000}});const page=await context.newPage();
 for(let i=0;i<60;i++){try{await page.goto('http://127.0.0.1:4192/?lang='+lang);break}catch{await new Promise(r=>setTimeout(r,100))}}await page.waitForSelector('.trail-card');
 const search=page.locator('.search-box input'),city=page.locator('.origin-city select'),sort=page.locator('.result-controls select');
 await city.selectOption('telaviv');await search.fill('ofer');await sort.selectOption('length');await page.reload();await page.waitForSelector('.trail-card');
 assert.equal(await city.inputValue(),'telaviv');assert.equal(await search.inputValue(),'ofer');assert.equal(await sort.inputValue(),'length');
 await page.locator('.category-tabs button').nth(1).click();await page.locator('.view-switch button').nth(1).click();await page.locator('.saved-filter').click();await page.reload();await page.waitForSelector('.search-panel');
 assert.equal(await page.locator('.category-tabs .chosen').count(),1);assert.equal(await page.locator('.view-switch button').nth(1).getAttribute('aria-pressed'),'true');assert(await page.locator('.saved-filter').evaluate(e=>e.classList.contains('active')));
 await page.locator('.preference-controls button').click();await page.waitForSelector('.trail-card');await page.reload();await page.waitForSelector('.trail-card');assert.equal(await city.inputValue(),'');assert.equal(await search.inputValue(),'');assert.equal(await sort.inputValue(),'default');assert.equal(await page.locator('.view-switch button').first().getAttribute('aria-pressed'),'true');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('.preference-controls').scrollIntoViewIfNeeded();await page.screenshot({path:folder+`/reset-${lang}-${width}.png`});
 await context.close();
 }
 const context=await browser.newContext();await context.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')}}));const page=await context.newPage();await page.goto('http://127.0.0.1:4192/?lang=en');await page.waitForSelector('.trail-card');await page.waitForSelector('text=This browser cannot save choices');await page.locator('.search-box input').fill('ofer');assert(await page.locator('.trail-card').count());await context.close();
 const gpsContext=await browser.newContext();await gpsContext.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(success){success({coords:{latitude:32.08,longitude:34.78,accuracy:20},timestamp:Date.now()})}}}));const gpsPage=await gpsContext.newPage();await gpsPage.goto('http://127.0.0.1:4192/?lang=en');await gpsPage.waitForSelector('.trail-card');await gpsPage.locator('.current-location-control button').click();await gpsPage.waitForSelector('.dynamic-origin');const stored=await gpsPage.evaluate(()=>localStorage.getItem('shvil-discovery-v1'));assert(!/32.08|34.78|origin|routed|fix/.test(stored));await gpsPage.reload();await gpsPage.waitForSelector('.trail-card');assert.equal(await gpsPage.locator('.dynamic-origin').count(),0);assert.equal(await gpsPage.locator('.origin-city select').inputValue(),'');await gpsContext.close();
 console.log('Preferences: reload, city/search/filter/sort/view/saved-only, reset, blocked storage, transient GPS, bilingual390/1440 passed');
}finally{await browser?.close();server.kill()}
